spring:
  application:
    name: spring-boot-config-client
  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8080
  profiles:
    active: dev

server:
  port: 8081