server:
  port: 8080

spring:
  application:
    name: spring-boot-config-server
  profiles:
    active: dev
  #    active: native - used when the config files exist in the config server's file system
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Acquah-Kingsley-Segu/Learning-Microservice-Architecture
          search-paths: /configs
        #        native:
#          search-locations: classpath:/config - used when the config files exist in the config server's file system
        accept-empty: false