spring:
  application:
    name: spring-boot-registry
  profiles:
    active: dev

server:
  port: 8082

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8082/eureka