spring:
  application:
    name: ${SERVER_NAME}

  profiles:
    active: dev

  config:
    import: optional:configserver:http://localhost:8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${SERVER_HOST}:${SERVER_PORT}/eureka

  instance:
    hostname: ${SERVER_HOST}