spring:
  application:
    name: ${SERVER_NAME}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${SERVER_HOST}:${SERVER_PORT}/eureka

  instance:
    hostname: ${SERVER_HOST}